# Generated by Django 4.1 on 2023-02-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainAPP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_patient",
            field=models.BooleanField(default=False),
        ),
    ]
